services:
  api:
    container_name: treasure-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "poetry run uvicorn src.main:app --host 0.0.0.0 --port $${PORT:-8000} --reload"
    networks:
      - treasure-network
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - ENVIRONMENT=${ENVIRONMENT}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_USERNAME=${SUPER_ADMIN_USERNAME}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}

  db:
    container_name: treasure-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: treasure
    volumes:
      - treasure-db-data:/var/lib/postgresql/data
    networks:
      - treasure-network

  redis:
    container_name: treasure-redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
      REDIS_DATABASE: 0
    volumes:
      - treasure-redis-data:/data
    networks:
      - treasure-network


volumes:
  treasure-db-data:
  treasure-redis-data:

networks:
  treasure-network:
    driver: bridge
